# Generated by Django 3.1.2 on 2020-10-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stand',
            old_name='model',
            new_name='make',
        ),
    ]
