# Generated by Django 3.1.2 on 2020-10-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201011_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='cost',
            field=models.IntegerField(max_length=6),
        ),
    ]
